### ISSUE TITLE
[vuex] Unknown mutation: global commit

### ISSUE THREAD

**Issue by kennethllamasares** [RashadSaleh/vuex-basement#2]
Hi i've tried using this to my existing project and i'm getting this error:

[vuex] Unknown mutation: global commit

My vuex store consists of different modules, where should i add the action global  commit?

> import Vue from 'vue'
> import Vuex from 'vuex'
> import modules from './modules'
> import basement from './basement'
> 
> Vue.use(Vuex)
> 
> console.log(modules)
> const store = new Vuex.Store({
>   modules,
>   strict: true,
>   actions: {
>   	'global commit': basement.global_commit
>   }
> })
> 
> console.log(store)
> 
> basement.attach_to_store(store)
> 
> console.log(basement)
> 
> export default store
>

**Comment by RashadSaleh** [comment]
Hey. `global commit`, despite the name, is actually an *action*. Judging from your error message, you need to `dispatch` rather than `commit` while using `global commit`.
